config/routes.rb
Rails.application.routes.draw do
  root to: 'trains#index'
  resources :trains do 
    collection { post :import }
  end
end

app/models/train.rb
class Train < ActiveRecord::Base
  validates_uniqueness_of :run_number, :scope => :operator_id
  validates :train_line, presence: true
  validates :route_name, presence: true
  validates :run_number, presence: true
  validates :operator_id, presence: true
  
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      lowercase_hash = {}
      row.to_hash.each do |key,value| 
        lowercase_hash.merge!({ key.downcase.strip => value })
      end
      Train.create(lowercase_hash)  
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  def index
    @trains = Train.all.sort_by{ |t| t.run_number.strip }
    @trains = Kaminari.paginate_array(@trains).page(params[:page]).per(5)                           
  end
  
  def new
    @train = Train.new
  end

  def create
    train = Train.new(params['id'])
    train.train_line = params['train']['train_line']
    train.route_name = params['train']['route_name']
    train.run_number = params['train']['run_number']
    train.operator_id = params['train']['operator_id']
    train.save
    redirect_to root_path, notice: 'Train ' + params['train']['run_number'] + ' Created'
  end

  def update
    train = Train.find(params['id'])
    train.train_line = params['train']['train_line']
    train.route_name = params['train']['route_name'] 
    train.run_number = params['train']['run_number'] 
    train.operator_id = params['train']['operator_id']
    train.save
    redirect_to root_path, notice: 'Train ' + params['train']['run_number'] + ' Updated'
  end
  
  def edit
    @train = Train.find(params['id'])
  end

  def destroy
    Train.destroy(params['id'])
    redirect_to root_path, notice: 'Train successfully deleted'
  end
  
  def import
    Train.import(params[:file])
    redirect_to root_path, notice: 'File Added Successfully, Congrats bro'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trains</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <center>
    <%= yield %>
  </center>
</body>
</html>

app/views/trains/edit.html.erb
<%= form_for @train, url: {action: "update", method: 'put'} do |f| %>
  <%= f.label :train_line %>
  <br/>
  <%= f.text_field :train_line %>
  <br/><br/>
  <%= f.label :route_name %>
  <br/>
  <%= f.text_field :route_name %>
  <br/><br/>
  <%= f.label :run_number %>
  <br/>
  <%= f.text_field :run_number %>
  <br/><br/>
  <%= f.label :operator_id %>
  <br/>
  <%= f.text_field :operator_id %>
  <br/><br/>
  <%= f.submit "Update" %>
<% end %>

app/views/trains/index.html.erb
<h1>Trains</h1>
<% if @trains.length > 0 %>
<table>
  <tr>
    <th><u>Train Line</u></th>
    <th><u>Route Name</u></th>
    <th><u>Run Number</u></th>
    <th><u>Operator ID</u></th>
  </tr>
  
  <% @trains.each do |t| %>
    <tr>
      <td> <%= t['train_line'] %> </td>
      <td> <%= t['route_name'] %> </td>
      <td> <%= t['run_number'] %> </td>
      <td> <%= t['operator_id'] %> </td>
      <td> <%= link_to 'edit', edit_train_path(t.id) %> </td>
      <td> <%= link_to "delete", t, method: :delete %> </td>
    </tr>
  <% end %>
 </table>
 <br/><br/>
 <%= paginate @trains %>
<% end %>

<h3>Add Trains</h3>
<%= link_to 'one train', new_train_path %>

<%= form_tag import_trains_path, multipart: true do %>
  <p><strong>A bunch of trains in csv format</strong></p>
  <%= file_field_tag :file %><br/>
  <%= submit_tag 'Upload csv file' %>
<% end %>
  

app/views/trains/new.html.erb
<%= form_for @train, url: {action: "create", method: 'post'} do |f| %>
  <%= f.label :train_line %>
  <br/>
  <%= f.text_field :train_line %>
  <br/><br/>
  <%= f.label :route_name %>
  <br/>
  <%= f.text_field :route_name %>
  <br/><br/>
  <%= f.label :run_number %>
  <br/>
  <%= f.text_field :run_number %>
  <br/><br/>
  <%= f.label :operator_id %>
  <br/>
  <%= f.text_field :operator_id %>
  <br/><br/>
  <%= f.submit "Create" %>
<% end %>